Textarea
Groww/ui-toolkit pull request #3
Opened 2021-05-04 20:32 UTC by AdityaVandan

Text area

2021-05-06 09:21 UTC, ankitchouhan1020 requested changes

2021-05-06 09:21 UTC, ankitchouhan1020 commented on src/components/atoms/TextArea/TextArea.tsx
> +    // bools for utility
migrate these comments in type Props.

2021-05-06 09:21 UTC, ankitchouhan1020 commented on src/components/atoms/TextArea/TextArea.tsx
> +  label?: string;
DefaultProps are optional by default. pass `label: ''` in defaultProps.

2021-05-06 09:21 UTC, ankitchouhan1020 commented on src/components/atoms/TextArea/TextArea.tsx
> +  onEnterPress: (e: React.KeyboardEvent) => void;
mark `e?: ..`

2021-05-06 09:21 UTC, ankitchouhan1020 commented on src/components/atoms/TextArea/TextArea.tsx
> +  onEnterPress: () => { },
onEnterPress and onBackspace press are user-specific requirements. Not needed in my opinion. Please check standard lib implementation too.

2021-05-07 10:22 UTC, AdityaVandan commented on src/components/atoms/TextArea/TextArea.tsx
> +type RequiredProps = {
not empty

2021-05-10 10:52 UTC, dheerajsingh123 commented on src/components/atoms/TextArea/TextArea.tsx
> +        showError &&
showError and error can be only one prop. Only error prop can determine if there is an error. If error === "", then don't show error.

2021-05-14 07:53 UTC, ankitchouhan1020 approved these changes

2021-05-14 07:54 UTC, merged