Radio button group
Groww/ui-toolkit pull request #7
Opened 2021-05-04 21:07 UTC by AdityaVandan

radio-button-group (taken from our codebase)

2021-05-10 11:47 UTC, ankitchouhan1020 commented on src/components/atoms/RadioButton/RadioButton.tsx
> +const RadioButton = (props: any) => {
fix prop type.

2021-05-11 07:08 UTC, dheerajsingh123 requested changes

2021-05-12 05:58 UTC, ankitchouhan1020 requested changes

2021-05-12 05:58 UTC, ankitchouhan1020 commented on src/components/atoms/RadioButton/RadioButton.tsx
> +  radioDirection: string,
`ValueOf<typeof RADIO_DIRECTION>` to be more precise.

2021-05-12 05:58 UTC, ankitchouhan1020 commented on src/components/atoms/RadioButton/RadioButton.tsx
> +  value?: React.ReactNode,
is it required or optional ?

2021-05-12 12:57 UTC, dheerajsingh123 approved these changes

2021-05-14 07:58 UTC, merged