scroll top with dummy content example
Groww/ui-toolkit pull request #9
Opened 2021-05-04 23:28 UTC by AdityaVandan

scroll-top (taken from codebase)

class component converted to functional component

2021-05-06 08:56 UTC, ankitchouhan1020 requested changes

2021-05-06 08:56 UTC, ankitchouhan1020 commented on src/utils/content/index.tsx
> +export const scrollTopDummyContent = () => (
```tsx
export const scrollTopDummyContent = () => (
  <div style={{ minHeight: 2000}}>Scroll to bottom</div>
)
```

2021-05-06 08:56 UTC, ankitchouhan1020 commented on stories/ScrollTop.stories.tsx
> +  argTypes: {
remove if not required.

2021-05-06 08:56 UTC, ankitchouhan1020 commented on stories/ScrollTop.stories.tsx
> +Default.args = {
remove if not required

2021-05-06 08:56 UTC, ankitchouhan1020 commented on src/components/atoms/ScrollTop/ScrollTop.tsx
> +type RequiredProps = {
remove if not required, use only DefaultProps

2021-05-07 09:59 UTC, AdityaVandan commented on src/utils/content/index.tsx
> +export const scrollTopDummyContent = () => (
done

2021-05-10 11:52 UTC, ankitchouhan1020 approved these changes

2021-05-12 08:58 UTC, dheerajsingh123 approved these changes

2021-05-14 07:55 UTC, merged